editor: source

execute:
  cache: false # "Danger, Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/.post-render.R"

title: "PMTilesBR"
keyword: >
  PMTiles, Vector Tiles, Raster Tiles, Tiled Data, Spatial Data, Data Science,
  Spatial Data Science, Geospatial Data Science, Spatial Visualization, Data
  Visualization, GIS, Open Data, Open Science, Reproducible Research,
  Tippecanoe, R Programming, Brazil

website:
  favicon: images/logo.svg
  site-url: https://cem-usp.github.io/pmtilesbr/
  repo-url: https://github.com/cem-usp/pmtilesbr/
  issue-url: https://github.com/cem-usp/pmtilesbr/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: Center for Metropolitan Studies
  repo-branch: main
  repo-actions: [edit, source, issue]
  sidebar: false
  search: false
  navbar:
    title: false
    background: "#070808"
    right:
      - icon: github
        href: https://github.com/cem-usp/pmtilesbr/
        aria-label: GitHub

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    locale: en
    language: en-us
    code-fold: false
    code-link: true
    code-tools: false
    df-print: paged
    fig-align: center
    cap-location: top
    callout-appearance: simple
    link-external-newwindow: true
    csl: csl/english-apa-author-date.csl
    theme: [cosmo, scss/styles.scss, brand]
    include-in-header:
      text: |
        <meta property="og:description" content="Geospatial tiled datasets for spatial visualization and analysis in Brazil.">
        <meta property="og:image" content="https://cem-usp.github.io/pmtilesbr/images/og-image.png">
        <meta property="og:image:height" content="2400">
        <meta property="og:image:width" content="1600">

google-scholar: true
bibliography: references.bib
