---
title: "PMTiles"
---

This repository hosts [PMTiles](https://docs.protomaps.com/pmtiles/) files to help with spatial visualization and analysis.

## Files

- World
  - Year: 2020
  - Resolution: 5
  - Version: latest
  - Minimum Zoom: 2
  - Maximum Zoom: 10
  - File: [`gadm-2020-world-resolution-5-version-latest-min-zoom-2-max-zoom-10.pmtiles`](pmtiles/gadm-2020-world-resolution-5-version-latest-min-zoom-2-max-zoom-10.pmtiles)

- Brazil
  - Year: 2020
  - Minimum Zoom: 2
  - Maximum Zoom: 10
  - Simplified: TRUE
  - File: [`geobr-2020-brazil-min-zoom-2-max-zoom-10-simplified.pmtiles`](pmtiles/geobr-2020-brazil-min-zoom-2-max-zoom-10-simplified.pmtiles)

- Brazil Regions
  - Year: 2020
  - Minimum Zoom: 2
  - Maximum Zoom: 10
  - Simplified: TRUE
  - File: [`geobr-2020-brazil-regions-min-zoom-2-max-zoom-10-simplified.pmtiles`](pmtiles/geobr-2020-brazil-regions-min-zoom-2-max-zoom-10-simplified.pmtiles)

- Brazil States
  - Year: 2020
  - Minimum Zoom: 2
  - Maximum Zoom: 10
  - Simplified: TRUE
  - File: [`geobr-2020-brazil-states-min-zoom-2-max-zoom-10-simplified.pmtiles`](pmtiles/geobr-2020-brazil-states-min-zoom-2-max-zoom-10-simplified.pmtiles)

- Brazil Municipalities
  - Year: 2024
  - Minimum Zoom: 2
  - Maximum Zoom: 10
  - Simplified: TRUE
  - File: [`geobr-2024-brazil-municipalities-min-zoom-2-max-zoom-10-simplified.pmtiles`](pmtiles/geobr-2024-brazil-municipalities-min-zoom-2-max-zoom-10-simplified.pmtiles)
